# Generated by Django 5.2 on 2025-04-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
    ]
