# Generated by Django 5.2 on 2025-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_produto_alter_mesa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
