# Generated by Django 5.2 on 2025-04-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_unitario',
        ),
    ]
